### ISSUE TITLE
Publish binaries to Github Releases

### ISSUE THREAD

**Issue by alexkreidler** [paradigmxyz/tbl#7]
This is an awesome tool thanks! It would be great to publish binaries so people can install super quickly with `cargo binstall tbl-cli` or even just `curl` if they don't have Rust setup on their machine.

You could use Github Workflows/Actions to build automatically when you either commit to main or tag a release. (And it could do cross platform builds for Linux x86, ARM, Mac, Windows) etc like this:

```yaml
  - name: build
    uses: actions-rs/cargo@v1
    with:
      command: build
      args: --release --target=${{ matrix.target }}
      use-cross: ${{ matrix.cross }}
```
